[package]
name = "nbd"
version = "0.1.0"
authors = ["00nktk <bananaelecitrus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
clap = "3.0.0-beta.1"